import {useState,useSyncExternalStore} from 'react';
import {RimDialog} from './RimDialog';
import {actualPrice,type RimworldController,type RimItem} from './controller';
function Details({item:x}:{item:RimItem}){return <details><summary>Подробнее о {x.label||x.name||x.def_name}</summary><p>{x.description||x.desc||'Игра пока не передала описание.'}</p>{x.tooltip&&<p>{x.tooltip}</p>}{x.source_mod&&<p>Мод: {x.source_mod}</p>}{x.has_archite&&<p>Архитные гены</p>}{x.genes&&<ul>{x.genes.map((g,i)=><li key={i}>{typeof g==='string'?g:g.label||g.def_name}</li>)}</ul>}</details>;}
export function CommerceView({controller:c}:{controller:RimworldController}){
  const s=useSyncExternalStore(c.subscribe,c.snapshot),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[modalSearch,setModalSearch]=useState(''),[eventSearch,setEventSearch]=useState('');
  const items=s.catalog.filter(x=>!['neurotrainer','xenotype'].includes(x.category||'')),categories=[...new Set(items.map(x=>x.category||'misc'))];
  const match=(x:RimItem,q:string)=>([x.label,x.name,x.def_name].join(' ')).toLowerCase().includes(q.trim().toLowerCase());
  const buy=(x:RimItem,source:'shop'|'xenotype'|'neurotrainer'='shop')=><article className="panel-card" key={x.def_name}><h4>{x.label||x.name||x.def_name}</h4><p>{x.category} · {actualPrice(x.price)?x.price+' 💎':'Цена не получена'}</p><Details item={x}/><button type="button" aria-label={'Купить '+(x.label||x.name||x.def_name)} disabled={s.busy||!actualPrice(x.price)} onClick={()=>void c.chooseItem(x,source)}>Купить {x.label||x.name||x.def_name}</button></article>;
  return <><section className="panel-card" aria-label="Магазин RimWorld"><h3>Магазин RimWorld</h3><label htmlFor="rw-shop-search">Поиск товаров</label><input id="rw-shop-search" value={search} onChange={e=>setSearch(e.currentTarget.value)}/><label htmlFor="rw-shop-category">Категория товаров</label><select id="rw-shop-category" value={category} onChange={e=>setCategory(e.currentTarget.value)}><option value="all">Все</option>{categories.map(x=><option key={x} value={x}>{x}</option>)}</select>{items.filter(x=>(category==='all'||(x.category||'misc')===category)&&match(x,search)).map(x=>buy(x))}{items.length===0&&<><p>Каталог пуст.</p><button type="button" onClick={()=>void c.loadCatalog()}>Обновить каталог</button></>}</section>
    <section className="panel-card" aria-label="События RimWorld"><h3>События</h3><label htmlFor="rw-event-search">Поиск событий</label><input id="rw-event-search" value={eventSearch} onChange={e=>setEventSearch(e.currentTarget.value)}/>{s.events.filter(x=>[x.name,x.id,x.category].join(' ').toLowerCase().includes(eventSearch.trim().toLowerCase())).map(x=><article key={x.id}><h4>{x.name}</h4><p>{x.category} · {actualPrice(x.cost)?x.cost+' 💎':'Цена не получена'}</p><button type="button" disabled={s.busy||!actualPrice(x.cost)} onClick={()=>c.chooseEvent(x)}>Заказать {x.name}</button></article>)}{!s.events.length&&<p>Каталог событий пуст.</p>}</section>
    {s.modal&&!s.confirmation&&<RimDialog title={s.modal==='passion'?'Огоньки страсти':s.modal==='neurotrainer'?'Нейротренеры':'Ксенотипы'} close={()=>{c.closeModal();setModalSearch('');}}><h3>{s.modal==='passion'?'Огоньки страсти':s.modal==='neurotrainer'?'Нейротренеры':'Ксенотипы'}</h3>{s.modal==='xenotype'&&<p>Текущий ксенотип не передан сервером. Выбор заменит текущие ксеногены; эндогены остаются.</p>}{s.modal!=='passion'?<><label htmlFor="rw-modal-search">Поиск в каталоге пешки</label><input id="rw-modal-search" value={modalSearch} onChange={e=>setModalSearch(e.currentTarget.value)}/>{s.modalItems.filter(x=>match(x,modalSearch)).map(x=>buy(x,s.modal as 'xenotype'|'neurotrainer'))}{!s.modalItems.length&&<p>Каталог пуст или ещё загружается.</p>}</>:s.skills.map(x=><article key={x.def_name}><h4>{x.label||x.def_name}</h4><p>Уровень {x.level} · страсть {x.passion} {x.is_disabled?'· недоступен':''}</p>{!x.is_disabled&&actualPrice(x.upgrade_price)&&<button type="button" aria-label={'Повысить страсть '+(x.label||x.def_name)} disabled={s.busy} onClick={()=>c.chooseSkill(x)}>Повысить · {x.upgrade_price} 💎</button>}{!x.is_disabled&&actualPrice(x.reset_price)&&<button type="button" aria-label={'Сбросить страсть '+(x.label||x.def_name)} disabled={s.busy} onClick={()=>c.chooseSkill(x,true)}>Сбросить · {x.reset_price} 💎</button>}</article>)}</RimDialog>}
    {s.side&&<section className="panel-card" role="dialog" aria-label="Сторона импланта"><h3>{s.side.item.label||s.side.item.def_name}: выбери сторону</h3>{(['left','right'] as const).map(part=><button type="button" key={part} aria-label={part==='left'?'Левая сторона':'Правая сторона'} onClick={()=>c.chooseSide(part)}>{part==='left'?'Левая':'Правая'} · {c.occupied(part)?'занята':'свободна'}</button>)}<button type="button" onClick={()=>c.cancel()}>Отмена</button></section>}
  </>;
}
