import { act } from '@testing-library/preact';
import { expect, it } from 'vitest';
import saved from './panel-fixtures/party-responses.json';
import { combatPair, flush, normalized } from './panel-combat-support';
import type { LegacyFixtures,LegacyJson,LegacyRequest } from './panel-legacy-harness';
const r=saved.responses;
const action=(q:LegacyRequest):LegacyJson=>{const b=q.body as {action_type:string;data:{order_type:string}};const key=b.action_type==='hero.party_order_set'?'order_'+b.data.order_type:({'hero.party_order_release':'order_release','hero.army_create':'army_create','hero.army_disband':'army_disband','hero.create_clan':'clan_create','hero.join_clan':'clan_join','hero.leave_clan':'clan_leave','hero.create_party':'create_party'} as Record<string,string>)[b.action_type];const item=(r as unknown as Record<string,{response:LegacyJson}>)[key];if(!item)throw new Error('Unknown party action '+JSON.stringify(b));return item.response;};
export const partyPair=(overrides:Partial<LegacyFixtures>={},tab:'hero'|'dynasty'='dynasty')=>combatPair({config:r.config,hero:r.hero_party,action,...overrides},false,tab,false,true);
type Pair=Awaited<ReturnType<typeof partyPair>>;
const hosts=(p:Pair):ParentNode[]=>[p.old.document,p.ui.container];
async function toggle(p:Pair,key:string,open=true){for(const host of hosts(p)){const n=host.querySelector<HTMLDetailsElement>(`[data-bnr-details="${key}"]`);expect(n).not.toBeNull();n!.open=open;n!.dispatchEvent(new (host===p.old.document?p.old.window.Event:Event)('toggle'));}await p.old.settle();await act(flush);}
async function choose(p:Pair,type:string){for(const host of hosts(p)){const n=host.querySelector<HTMLInputElement>(`input[name="bnr-order-type"][value="${type}"]`);expect(n).not.toBeNull();n!.checked=true;n!.dispatchEvent(new (host===p.old.document?p.old.window.Event:Event)('change',{bubbles:true}));}await p.old.settle();await act(flush);}
async function input(p:Pair,q:string,value:string,enter=false){for(const host of hosts(p)){const n=host.querySelector<HTMLInputElement>(q);expect(n).not.toBeNull();n!.value=value;n!.dispatchEvent(new (host===p.old.document?p.old.window.Event:Event)('input',{bubbles:true}));if(enter)n!.dispatchEvent(new (host===p.old.document?(p.old.window as unknown as Window&{KeyboardEvent:typeof KeyboardEvent}).KeyboardEvent:KeyboardEvent)('keydown',{key:'Enter',bubbles:true}));}await p.old.settle();await act(flush);}
const posts=(p:Pair)=>p.trace.filter(q=>q.path.endsWith('/action'));
it('production selected host restores dynasty with exact initial and 8s active-only reads',async()=>{const p=await partyPair();p.check();expect(p.ui.getByRole('button',{name:'Клан, отряд и армия'}).getAttribute('aria-pressed')).toBe('true');await p.advance(8000);p.check();await p.tab('hero');await p.advance(8000);p.check();await p.tab('dynasty');p.check();});
for(const type of ['siege','defend','raid','garrison','patrol'])it(`strategic ${type} exact target decoration and complete 2s/3.5s tails`,async()=>{const p=await partyPair();await toggle(p,'party-order');await choose(p,type);expect(p.ui.container.querySelector('#bnr-order-target-select')?.textContent).toBe(p.old.document.querySelector('#bnr-order-target-select')?.textContent);await p.click('#bnr-order-confirm');await p.advance(3500);p.check();expect(posts(p)).toHaveLength(1);});
it('recruit hides target and sends empty strings; old placeholder defect remains an explicit exception',async()=>{const p=await partyPair();await toggle(p,'party-order');await choose(p,'recruit');expect(p.ui.container.querySelector('#bnr-order-target-select')).toBeNull();await p.click('#bnr-order-confirm');expect((posts(p)[0].body as {data:object}).data).toMatchObject({order_type:'recruit',target_settlement_id:'',target_settlement_name:''});expect((p.old.trace.find(q=>q.path.endsWith('/action'))!.body as {data:object}).data).toMatchObject({target_settlement_name:'— нет доступных целей —'});});
it('release preserves real 1.5s explicit hidden read plus generic 3.5s tail',async()=>{const p=await partyPair({partyOrders:r.orders_siege});await p.click('#bnr-order-cancel');await p.hide(true);await p.advance(3500);p.check();expect(posts(p)).toHaveLength(1);});
for(const [hero,q] of [[r.hero_party,'[data-bnr-action="army_create"]'],[r.hero_no_party,'.bnr-clan-party']] as const)it(`complete ${q} action and full success tails`,async()=>{const p=await partyPair({hero});await p.click(q);await p.advance(3500);p.check();expect(posts(p)).toHaveLength(1);});
for(const [hero,q] of [[r.hero_army_leader,'[data-bnr-action="army_disband"]'],[r.hero_clan_member,'.bnr-locked-leave'],[r.hero_party,'.bnr-clan-leave']] as const)for(const yes of [false,true])it(`real danger modal ${q} answer ${yes}`,async()=>{const p=await partyPair({hero});await p.click(q);expect(posts(p)).toHaveLength(0);const oldText=p.old.document.querySelector('#confirm-dyn-modal')?.textContent;expect(p.ui.container.querySelector('#confirm-dyn-modal')?.textContent).toBe(oldText);await p.click(yes?'#confirm-dyn-yes':'#confirm-dyn-no');await p.advance(3500);p.check();expect(posts(p)).toHaveLength(yes?1:0);});
for(const type of ['create','join'] as const)it(`clan ${type} trim and Enter exact payload`,async()=>{const p=await partyPair({hero:r.hero_clanless});await toggle(p,type==='create'?'locked-create':'locked-join');await input(p,type==='create'?'#bnr-clan-name-input':'#bnr-join-name-input','  Fixture Clan  ',true);await p.advance(3500);p.check();expect(posts(p)).toHaveLength(1);});
it('draft survives changing active orders on ordinary poll and target lists are preselected',async()=>{const p=await partyPair({partyOrders:r.orders_siege});await toggle(p,'party-order');await choose(p,'patrol');p.fixtures.partyOrders=r.orders_defend;await p.advance(8000);expect((p.ui.container.querySelector('input[name="bnr-order-type"]:checked') as HTMLInputElement)?.value).toBe('patrol');p.check();});
it('server refusal keeps exact message and still performs local order-read tail',async()=>{const p=await partyPair({action:r.order_cooldown.response});await toggle(p,'party-order');await p.click('#bnr-order-confirm');expect(p.ui.container.textContent).toContain(r.order_cooldown.response.message);await p.advance(3500);p.check();});
it('empty lists stay select-mode with no made-up target or POST',async()=>{const hero={...r.hero_party,hero:{...r.hero_party.hero,kingdom_info:{...r.hero_party.hero.kingdom_info,own_settlements:[],enemy_settlements:[]}}};const p=await partyPair({hero});await toggle(p,'party-order');await p.click('#bnr-order-confirm');p.check();expect(posts(p)).toHaveLength(0);});
it('absent lists permit manual target, trimmed with inherited three-character check',async()=>{const hero={...r.hero_party,hero:{...r.hero_party.hero,kingdom_info:{...r.hero_party.hero.kingdom_info,own_settlements:null,enemy_settlements:null}}};const p=await partyPair({hero});await toggle(p,'party-order');await input(p,'#bnr-order-target-name',' x ');await p.click('#bnr-order-confirm');expect(posts(p)).toHaveLength(0);await input(p,'#bnr-order-target-name','  Lycaron  ');await p.click('#bnr-order-confirm');await p.advance(3500);p.check();expect(posts(p)).toHaveLength(1);});
it('hidden dynasty suppresses ordinary polls, restored show resumes at next hero cadence',async()=>{const p=await partyPair();await p.hide(true);await p.advance(16000);p.check();await p.hide(false);await p.advance(8000);p.check();});
export {r, toggle,choose,input,posts,normalized};
