import {act,cleanup,render} from '@testing-library/preact';
import {afterEach,expect,it,vi} from 'vitest';
import {SocialFamilyView} from '../src/common/SocialFamilyView';
import {pair,flush,disposePairs} from './panel-shell-pair';
import saved from './panel-fixtures/social-family-responses.json';
import type {LegacyFixture} from './panel-legacy-harness';
const r=saved.responses;
afterEach(()=>{cleanup();disposePairs();vi.useRealTimers();});
async function setup(married=false,overrides:Record<string,LegacyFixture>={}){
  const p=await pair({'GET /api/core/config':r.config,'GET /api/marriage/status/alice':married?r.married:r.single,'GET /api/marriage/proposals/alice':r.proposals,'POST /api/marriage/propose':r.propose,'POST /api/marriage/reject':r.reject,'POST /api/marriage/divorce':r.divorce,'POST /api/marriage/accept':r.accept_wrong_target.response,...overrides});
  await p.old.click('[data-action="family"]');document.dispatchEvent(new Event('click'));const ui=render(<SocialFamilyView runtime={p.runtime}/>);await act(flush);p.check();
  return {...p,ui,async click(old:string,label:string){await p.old.click(old);await act(async()=>{ui.getByRole('button',{name:label,exact:true}).click();await flush();});}};
}
it('social family reads only actual status proposals and online viewers in original order',async()=>{const p=await setup();expect(p.ui.container.textContent).toContain('@bob');expect(p.ui.container.textContent).toContain('@carol');expect(p.ui.getByLabelText('Кому предложить брак',{exact:true}).textContent).toContain('bob');});
it('social family proposal retains selected user raw payload and closes without balance reads',async()=>{const p=await setup();(p.old.document.querySelector('#family-target') as HTMLSelectElement).value='bob';await act(async()=>{const select=p.ui.getByLabelText('Кому предложить брак',{exact:true}) as HTMLSelectElement;select.value='bob';select.dispatchEvent(new Event('change',{bubbles:true}));await flush();});expect((p.ui.getByRole('button',{name:'Предложить',exact:true}) as HTMLButtonElement).disabled).toBe(false);await p.click('[data-action="propose-family"]','Предложить');await act(async()=>{await p.advance(60000);});p.check();expect(p.ui.getByRole('status').textContent).toContain('Ждём ответа');expect(p.trace.find(q=>q.path==='/api/marriage/propose')?.rawBody).toBe('{"username":"alice","target":"bob"}');});
it('social family reject targets exactly the chosen proposer and reloads all original branches',async()=>{const p=await setup();p.routes['GET /api/marriage/proposals/alice']=r.empty_proposals;await p.click('[data-reject-family="bob"]','Отклонить @bob');p.check();expect(p.ui.container.querySelector('[data-reject-family="bob"]')).toBeNull();expect(p.trace.find(q=>q.path==='/api/marriage/reject')?.rawBody).toBe('{"from_user":"bob"}');});
it('social family divorce confirms real core price and preserves full minute traffic',async()=>{const p=await setup(true);await p.click('[data-action="divorce-family"]','Развестись');expect(p.ui.getByRole('dialog').textContent).toContain(String(r.config.divorce_cost));expect(p.trace.some(q=>q.path==='/api/marriage/divorce')).toBe(false);await p.click('#confirm-dyn-yes','Подтвердить');await act(async()=>{await p.advance(60000);});p.check();expect(p.trace.find(q=>q.path==='/api/marriage/divorce')?.rawBody).toBe('{"username":"alice"}');});
it('social family divorce refusal preserves unknown server text with no success refresh',async()=>{const p=await setup(true,{'POST /api/marriage/divorce':{success:false,message:'Сервер отказал по новой причине'}});await p.click('[data-action="divorce-family"]','Развестись');await p.click('#confirm-dyn-yes','Подтвердить');p.check();expect(p.ui.getByRole('status').textContent).toContain('Сервер отказал по новой причине');});
it('social family absent divorce quote never copies the old literal500',async()=>{const p=await setup(true,{'GET /api/core/config':{}});expect((p.ui.getByRole('button',{name:'Развестись'}) as HTMLButtonElement).disabled).toBe(true);expect(p.ui.container.textContent).toContain('Цена развода не получена');});
it('social family blocks accept because real route ignores chosen proposer and marries another user',async()=>{const p=await setup();const proof=r.accept_wrong_target;expect(proof.request.from_user).toBe('bob');expect(proof.status.partner).toBe('carol');expect(proof.response.success).toBe(true);const button=p.ui.getByRole('button',{name:'Принять @bob'}) as HTMLButtonElement;expect(button.disabled).toBe(true);button.click();await act(flush);p.check();expect(p.trace.some(q=>q.path==='/api/marriage/accept')).toBe(false);expect(p.ui.container.textContent).toContain('не подтверждает выбранного человека');});
