import {act} from '@testing-library/preact';
import {expect,it} from 'vitest';
import {heroPair} from './panel-hero-support';
import {nextResponseTurn} from './panel-response-order';
import type {LegacyFixture,LegacyFixtures} from './panel-legacy-harness';
import saved from './panel-fixtures/commerce-responses.json';
import game from './panel-fixtures/game-progression-responses.json';
const r=saved.responses,g=game.responses;
async function pair(overrides:Partial<LegacyFixtures>={}){
  const routes:Record<string,LegacyFixture>={'GET /api/bannerlord/shop':r.shop,'GET /api/bannerlord/status':r.status};
  const p=await heroPair({config:r.config,hero:r.hero,classes:r.classes,action:q=>{const b=q.body as {action_type:string;data:{price?:number}};if(b.action_type==='player.give_item')return r.config.give_gold_presets.findIndex(x=>x.crusticov===b.data.price)===0?r.gold_0.response:b.data.price===r.config.give_gold_presets[1].crusticov?r.gold_1.response:r.gold_2.response;return b.action_type==='hero.add_skill'?g.xp_success.response:b.action_type==='hero.upgrade_gear'?r.upgrade.response:b.action_type==='hero.reequip_gear'?r.reequip.response:b.action_type==='hero.discard_item'?r.discard.response:r.catalog_buy.response;},...overrides},{commerceHost:true,extraRoutes:routes});
  return {...p,routes};
}
type Pair=Awaited<ReturnType<typeof pair>>;
const posts=(p:Pair)=>p.trace.filter(q=>q.method==='POST');
async function buy(p:Pair,selector:string){await p.old.click(selector);await p.newClick(selector);expect(posts(p)).toHaveLength(0);await p.confirm();await p.finish();}
async function funded(p:Pair){await p.old.refreshBalance();await act(async()=>{await p.controller.refreshBalance();});await p.old.refreshShop();await act(async()=>{await p.controller.refreshShop();});await act(nextResponseTurn);}
it('Bannerlord commerce boots actual shop progression and connection status in original request order',async()=>{const p=await pair();p.check();expect(p.ui.getByRole('region',{name:'Магазин Bannerlord'}).textContent).toContain('Собрать армию');expect(p.ui.getByRole('region',{name:'Магазин Bannerlord'}).textContent).not.toContain('Устаревший опыт');expect(p.ui.getByLabelText('Подключение Bannerlord').textContent).toContain('Онлайн');});
for(const i of [0,1,2] as const)it(`Bannerlord gold offer ${i} keeps exact preset and hero action tail`,async()=>{const p=await pair();await funded(p);await buy(p,`[data-bnr-givegold="${r.config.give_gold_presets[i].crusticov}"]`);expect(posts(p)[0].body).toMatchObject(r['gold_'+i as 'gold_0'].request);});
it('Bannerlord shop XP uses the personal game quote and exact context',async()=>{const p=await pair();await funded(p);await buy(p,`[data-bnr-skillxp="${g.progression.xp_offers[0].id}"]`);expect(posts(p)[0].body).toMatchObject(g.xp_success.request);});
it('Bannerlord optional catalog uses actual action price and generic continuation',async()=>{const p=await pair();await funded(p);await buy(p,'[data-bnr-buy="hero.army_create"]');expect(posts(p)[0].body).toMatchObject(r.catalog_buy.request);});
for(const kind of ['upgrade','reequip'] as const)it(`Bannerlord legacy gear ${kind} keeps empty payload and full continuation`,async()=>{const p=await pair();await p.old.refreshHero();await act(async()=>{await p.controller.refreshHero();});await act(nextResponseTurn);await buy(p,kind==='upgrade'?'#bnr-inline-upgrade-btn':'#bnr-reequip-btn');expect(posts(p)[0].body).toMatchObject(r[kind].request);});
it('Bannerlord gear refusal preserves server message and no success tails',async()=>{const p=await pair({action:r.upgrade_refused.response});await p.old.refreshHero();await act(async()=>{await p.controller.refreshHero();});await act(nextResponseTurn);await buy(p,'#bnr-inline-upgrade-btn');expect(p.ui.container.textContent).toContain(r.upgrade_refused.response.message);});
it('Bannerlord shop changed quote revokes a displayed paid confirmation',async()=>{const p=await pair();await funded(p);await p.newClick('[data-bnr-buy="hero.army_create"]');p.routes['GET /api/bannerlord/shop']={...r.shop,items:r.shop.items.map(i=>({...i,price:1234}))};await p.old.refreshShop();await act(async()=>{await p.controller.refreshShop();});await act(nextResponseTurn);p.check();expect(p.ui.queryByRole('dialog')).toBeNull();expect(posts(p)).toHaveLength(0);});
it('Bannerlord absent gold presets never copy the legacy fallback price list',async()=>{const config={...r.config,give_gold_presets:[]};const p=await pair({config});p.check();expect(p.ui.container.querySelector('[data-bnr-givegold]')).toBeNull();expect(p.ui.getByRole('region',{name:'Магазин Bannerlord'}).textContent).toContain('Предложения динаров не получены');});
it('Bannerlord new equipment store hides the old tier and reroll controls',async()=>{const p=await pair({hero:{...r.hero,equipment_shop_ready:true}});p.check();expect(p.ui.container.querySelector('#bnr-inline-upgrade-btn')).toBeNull();expect(p.ui.container.querySelector('#bnr-reequip-btn')).toBeNull();});
it('Bannerlord hero summary keeps observed location culture wins and armor totals',async()=>{const p=await pair();p.check();const summary=p.ui.getByRole('region',{name:'Карточка героя'});expect(summary.textContent).toContain('Город фикстуры');expect(summary.textContent).toContain('Культура фикстуры');expect(summary.textContent).toContain('Голова: 17');expect(summary.textContent).toContain('Тело: 3');expect(summary.textContent).toContain('Побед в турнирах: 3');expect(p.ui.getByRole('region',{name:'Надетые вещи прежнего режима'}).textContent).toContain('mod_stat: 19');});
it('Bannerlord legacy discard names the observed item and preserves exact slot-only wire',async()=>{const p=await pair();await p.old.click('.bnr-discard-btn[data-slot="head"]');await p.newClick('.bnr-discard-btn[data-slot="head"]');expect(p.ui.getByRole('dialog').textContent).toContain('Шлем фикстуры');expect(posts(p)).toHaveLength(0);await p.old.click('#confirm-dyn-yes');await p.confirm();await p.finish();expect(posts(p)[0].body).toMatchObject(r.discard.request);});
it('Bannerlord legacy discard cannot delete a replacement item in the observed slot',async()=>{const p=await pair();await p.newClick('.bnr-discard-btn[data-slot="head"]');p.fixtures.hero={...r.hero,equipment:{head:{...r.hero.equipment.head,item_id:'replacement',item_name:'Другой шлем'}}};await p.old.refreshHero();await act(async()=>{await p.controller.refreshHero();});await act(nextResponseTurn);p.check();expect(p.ui.queryByRole('dialog')).toBeNull();expect(posts(p)).toHaveLength(0);});
