<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Util/InventorySnapshotPublisher.cs" Link="InventorySnapshotPublisher.cs" />
    <Compile Include="../../src/Util/ReforgeQuality.cs" Link="ReforgeQuality.cs" />
    <Compile Include="../../src/Actions/ReforgeQualityHandler.cs" Link="ReforgeQualityHandler.cs" />
    <Compile Include="../../src/Behaviors/EquipmentShopBehavior.cs" Link="EquipmentShopBehavior.cs" />
    <Compile Include="../../src/Actions/EquipmentShopHandlers.cs" Link="EquipmentShopHandlers.cs" />
    <Compile Include="../../src/Util/EquipmentShopPolicy.cs" Link="EquipmentShopPolicy.cs" />
    <Compile Include="../../src/Util/EquipmentSessionHandshake.cs" Link="EquipmentSessionHandshake.cs" />
    <Compile Include="../../src/Util/HeroGoldCharge.cs" Link="HeroGoldCharge.cs" />
    <Compile Include="../../src/Util/OwnPartyInventory.cs" Link="OwnPartyInventory.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
