import type {ViewerRuntime} from './runtime';
export type CommunityGame='rps'|'tictactoe'|'tug';
type Side='a'|'b';
export interface Board {cells:(string|null)[];next_turn:Side;winner?:string|null}
export interface GameRoom {room_id:string;status:string;you_are:Side;opponent:string;player_a_elo:number;player_b_elo:number;winner?:string|null;outcome?:string|null;state:{version:number;phase:string;rounds_total:number;current_round:number;board_size?:number;boards?:Board[];moves?:Record<Side,(string|null)[]>;round_outcomes?: (string|null)[];wins:Record<Side,number>;deadline_at?:string|null;rating?:{before:Record<Side,number>;after:Record<Side,number>;delta:Record<Side,number>}}}
export interface Queue {success:boolean;status:string;room_id?:string;queue_position?:number;elo_at_queue?:number;queued?:boolean;in_queue?:boolean;message?:string;reason?:string}
export interface Leaderboard {leaderboard?:{rank?:number;username:string;elo:number;win_streak?:number}[];ends_at?:string|null;prizes?:Record<string,number>;elo_gate?:number}
export interface TugState {success:boolean;message?:string;room?:{room_id:string;status:string;opponent:string;seconds_left:number;my_side:Side;pos:number;my_eff:number;opponent_eff:number;my_taps:number;next_tap_value:number;outcome?:string|null}|null;rules?:{formula_ru?:string;reward_ru?:string;match_sec?:number;rope_limit?:number};leaderboard?:Leaderboard['leaderboard'];season_ends_at?:string|null}
interface Reply {success:boolean;message?:string;reason?:string;room?:GameRoom;state?:GameRoom['state'];status?:string;winner?:string|null;outcome?:string|null;finished?:boolean}
export interface GameViewState {mode:'lobby'|'game';queue:Queue|null;room:GameRoom|null;tug:TugState|null;leaderboard:Leaderboard|null;message:string;busy:boolean;closed:boolean;now:number}
/** Owns timers and exact legacy continuations; only the server decides game outcomes. */
export class CommunityGameController {
  private data:GameViewState={mode:'game',queue:null,room:null,tug:null,leaderboard:null,message:'',busy:false,closed:false,now:Date.now()};
  private listeners=new Set<()=>void>();private active=false;private owner='';private roomId:string|null=null;
  private poll:ReturnType<typeof setInterval>|undefined;private ticker:ReturnType<typeof setInterval>|undefined;private timers=new Set<ReturnType<typeof setTimeout>>();private batch:ReturnType<typeof setTimeout>|undefined;
  private pending=0;private batchRoom='';private revision=0;private applied=0;private barrier=0;private locked=false;
  constructor(readonly game:CommunityGame,private runtime:ViewerRuntime){this.data.mode=game==='rps'?'lobby':'game';}
  snapshot=()=>this.data;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
  private publish(patch:Partial<GameViewState>){this.data={...this.data,...patch};this.listeners.forEach(fn=>fn());}
  private identity(){const i=this.runtime.snapshot().client?.identity;return i?JSON.stringify([i.channelId,i.login]):'';}
  private valid=()=>this.active&&this.identity()===this.owner&&!this.data.closed;
  private error=(e:unknown)=>{if(this.valid())this.publish({message:e instanceof Error?e.message:'Сеть недоступна. Результат запроса неизвестен.'});};
  private later(fn:()=>void,ms:number){const t=setTimeout(()=>{this.timers.delete(t);if(this.valid())fn();},ms);this.timers.add(t);return t;}
  private stopPoll(){clearInterval(this.poll);clearInterval(this.ticker);this.poll=this.ticker=undefined;}
  private startPoll(){this.stopPoll();if(!this.valid())return;if(this.game!=='tug')this.ticker=setInterval(()=>this.publish({now:Date.now()}),200);this.poll=setInterval(()=>{void(this.game==='tug'?this.refreshTug():this.roomId?this.refreshRoom(this.roomId):this.refreshQueue());},2000);}
  private clearBatch(){clearTimeout(this.batch);this.batch=undefined;this.pending=0;this.batchRoom='';}
  async start(){if(this.active)return;this.active=true;this.owner=this.identity();if(this.game==='rps'){const client=this.runtime.snapshot().client;if(!client)return;try{const [,leaderboard]=await Promise.all([client.read('/api/duel/list'),client.read<Leaderboard>('/api/duel/leaderboard')]);if(this.valid())this.publish({leaderboard});}catch(e){this.error(e);}return;}
    if(this.game==='tictactoe')void this.loadLeaderboard();await(this.game==='tug'?this.refreshTug():this.refreshQueue());if(this.valid())this.startPoll();
    if(this.game==='tictactoe')this.unsubscribe=this.runtime.realtime.subscribe('match_state',data=>{const hint=data as {room_id?:string;game?:string};if(this.valid()&&this.roomId&&hint.room_id===this.roomId&&hint.game===this.game)void this.refreshQueue();});
  }
  private unsubscribe:(()=>void)|undefined;
  async enterRps(){if(!this.valid()||this.data.mode!=='lobby')return;this.publish({mode:'game'});await this.refreshQueue();if(this.valid())this.startPoll();}
  private async loadLeaderboard(){const client=this.runtime.snapshot().client;if(!client||!this.valid())return;try{const leaderboard=await client.read<Leaderboard>('/api/tictactoe/leaderboard');if(this.valid()&&this.runtime.snapshot().client===client)this.publish({leaderboard});}catch(e){this.error(e);}}
  private setRoom(room:GameRoom|null){this.roomId=room?.room_id||null;this.publish({room});if(room&&(room.status!=='active'||room.state.phase==='finished'))this.stopPoll();}
  private async refreshQueue(){const client=this.runtime.snapshot().client;if(!client||!this.valid())return;const seq=++this.revision,barrier=this.barrier;try{const queue=await client.read<Queue>('/api/match/queue/status?game_type='+this.game);if(!this.valid()||client!==this.runtime.snapshot().client||barrier!==this.barrier||seq<this.applied)return;this.applied=seq;this.publish({queue});if(queue.success&&(queue.status==='matched'||queue.status==='in_room')&&queue.room_id){this.roomId=queue.room_id;await this.refreshRoom(queue.room_id);}else if(!queue.success||queue.status==='idle')this.setRoom(null);}catch(e){this.error(e);}}
  private async refreshRoom(id:string){const client=this.runtime.snapshot().client;if(!client||!this.valid())return;const seq=++this.revision,barrier=this.barrier;try{const reply=await client.read<Reply>('/api/'+this.game+'/poll?room_id='+encodeURIComponent(id));if(!this.valid()||client!==this.runtime.snapshot().client||barrier!==this.barrier||seq<this.applied||this.roomId!==id)return;this.applied=seq;if(reply.success&&reply.room)this.setRoom(reply.room);else{this.setRoom(null);this.publish({queue:{success:true,status:'idle'},message:reply.message||reply.reason||'Комната недоступна'});}}catch(e){this.error(e);}}
  private async refreshTug(){const client=this.runtime.snapshot().client;if(!client||!this.valid())return;const seq=++this.revision,barrier=this.barrier;try{const [tug,queue]=await Promise.all([client.read<TugState>('/api/tug/status'),client.read<Queue>('/api/match/queue/status?game_type=tug')]);if(!this.valid()||client!==this.runtime.snapshot().client||barrier!==this.barrier||seq<this.applied)return;this.applied=seq;if(this.batchRoom&&(tug.room?.room_id!==this.batchRoom||tug.room?.status!=='active'))this.clearBatch();this.publish({tug,queue});}catch(e){this.error(e);}}
  async queue(cancel=false){const client=this.runtime.snapshot().client;if(!client||!this.valid()||this.locked)return;this.locked=true;this.publish({busy:true});this.barrier++;try{const reply=await client.post<Reply>('/api/match/queue'+(cancel?'/cancel':''),{game_type:this.game});if(!this.valid()||client!==this.runtime.snapshot().client)return;if(reply.message||!reply.success)this.publish({message:reply.message||reply.reason||'Сервер отказал в действии'});if(this.game==='tug')await this.refreshTug();else if(cancel||reply.success)await this.refreshQueue();}catch(e){this.error(e);}finally{this.locked=false;if(this.valid())this.publish({busy:false});}}
  canMove(){const room=this.data.room;if(!room||!this.valid()||this.locked||room.status!=='active'||room.state.version!==2||room.state.phase==='finished')return false;return this.game==='rps'?!room.state.moves?.[room.you_are]?.[room.state.current_round-1]:room.state.boards?.at(-1)?.next_turn===room.you_are;}
  async move(value:string|number,seen:GameRoom){const client=this.runtime.snapshot().client,room=this.data.room;if(!client||!this.canMove()||room!==seen||(this.game==='tictactoe'&&room.state.boards?.at(-1)?.cells[Number(value)]))return;this.locked=true;this.barrier++;this.publish({busy:true});try{const reply=await client.post<Reply>('/api/'+this.game+'/move',this.game==='rps'?{room_id:room.room_id,move:value}:{room_id:room.room_id,cell:value});if(!this.valid()||client!==this.runtime.snapshot().client||this.roomId!==room.room_id)return;if(!reply.success){this.publish({message:reply.message||reply.reason||'Не удалось сделать ход'});return;}if(this.game==='rps')await this.refreshRoom(room.room_id);else if(reply.state){this.setRoom({...room,state:reply.state,status:reply.status||room.status,winner:reply.winner,outcome:reply.outcome});if(reply.finished){this.publish({message:reply.message||'Матч завершён'});void this.loadLeaderboard();this.later(()=>{void this.runtime.snapshot().client?.refreshUser().catch(this.error);},500);}}}catch(e){this.error(e);}finally{this.later(()=>{this.locked=false;this.publish({busy:false});},this.game==='rps'?400:600);}}
  again(){if(!this.valid())return;this.barrier++;this.setRoom(null);this.publish({queue:{success:true,status:'idle'}});this.startPoll();if(this.game==='tictactoe'){void this.loadLeaderboard();this.later(()=>{void this.runtime.snapshot().client?.refreshUser().catch(this.error);},500);}}
  pull(seen:TugState['room']){if(!this.valid()||!seen||seen!==this.data.tug?.room||seen.status!=='active')return;this.pending++;this.batchRoom=seen.room_id;if(this.batch)return;this.batch=this.later(()=>{this.batch=undefined;const taps=this.pending;this.pending=0;const id=this.batchRoom;this.batchRoom='';if(this.data.tug?.room?.room_id!==id||this.data.tug?.room?.status!=='active')return;const client=this.runtime.snapshot().client;if(!client)return;void client.post<Reply>('/api/tug/pull',{taps}).then(async reply=>{if(!this.valid()||this.runtime.snapshot().client!==client)return;if(!reply.success)this.publish({message:reply.message||reply.reason||'Рывок не принят'});await this.refreshTug();}).catch(this.error);},1000);}
  close(){if(!this.valid())return;if(this.game==='rps'&&this.data.mode==='game')void this.runtime.snapshot().client?.post('/api/match/queue/cancel',{game_type:'rps'}).catch(()=>{});this.publish({closed:true});this.stop();}
  stop(){this.active=false;this.stopPoll();this.clearBatch();this.unsubscribe?.();this.timers.forEach(clearTimeout);this.timers.clear();}
}
