import {useLayoutEffect,useMemo,useSyncExternalStore} from 'react';
import type {ViewerRuntime} from './runtime';
import {CommunityGameController,type CommunityGame,type Leaderboard} from './community-games';
export type {CommunityGame} from './community-games';
const moves:Record<string,string>={rock:'🪨 Камень',paper:'📄 Бумага',scissors:'✂️ Ножницы'};
function Season({data}:{data:Leaderboard|null}){return <details><summary>Рейтинг сезона</summary>{data?.ends_at&&<p>Сезон до {new Date(data.ends_at).toLocaleDateString('ru-RU')}</p>}{data?.prizes&&<p>Призы в конце сезона: {Object.entries(data.prizes).map(([place,amount])=>`${place} место: ${amount.toLocaleString('ru-RU')} 💎`).join(' · ')}</p>}{typeof data?.elo_gate==='number'&&<p>Порог приза: {data.elo_gate} ELO</p>}{data?.leaderboard?.length?<ol>{data.leaderboard.map(row=><li key={row.username}>@{row.username} · {row.elo} ELO{row.win_streak?' · серия '+row.win_streak:''}</li>)}</ol>:<p>Пока никто не играл.</p>}</details>;}
export function CommunityGamesView({runtime,game,onClose}:{runtime:ViewerRuntime;game:CommunityGame;onClose?:()=>void}){
  const {client}=useSyncExternalStore(runtime.subscribe,runtime.snapshot),owner=client?client.identity.channelId+':'+client.identity.login:'';
  const controller=useMemo(()=>new CommunityGameController(game,runtime),[game,runtime,owner]),s=useSyncExternalStore(controller.subscribe,controller.snapshot);
  useLayoutEffect(()=>{void controller.start();return()=>controller.stop();},[controller]);
  if(s.closed)return null;
  const room=s.room,st=room?.state,finished=room&&(room.status!=='active'||st?.phase==='finished'),you=room?.you_are||'a',op=you==='a'?'b':'a';
  const queued=s.queue?.status==='queued'||s.queue?.queued||s.queue?.in_queue,tug=s.tug,tr=tug?.room,limit=tug?.rules?.rope_limit;
  const seconds=st?.deadline_at?Math.max(0,Math.ceil((Date.parse(st.deadline_at)-s.now)/1000)):null;
  const prefix=game==='tictactoe'?'ttt':game;
  return <section className="panel-card" aria-label={game==='rps'?'Дуэли':game==='tug'?'Канат':'Крестики-нолики'}><h2>{game==='rps'?'Дуэли · камень, ножницы, бумага':game==='tug'?'Канат':'Крестики-нолики'}</h2>{s.message&&<p role="status">{s.message}</p>}
    {s.mode==='lobby'?<><p>Найди соперника для дуэли. Рейтинг и сезонные награды — по результатам игр.</p><button type="button" id="duel-find-btn" onClick={()=>void controller.enterRps()}>Найти противника</button></>:game==='tug'?<>
      {tr?.status==='active'?<><p>Соперник: @{tr.opponent} · осталось {tr.seconds_left} с</p>{typeof limit==='number'&&limit>0&&<meter aria-label="Положение каната" min={-limit} max={limit} value={Math.max(-limit,Math.min(limit,tr.my_side==='a'?tr.pos:-tr.pos))}/>}<p>Твоя сила: {tr.my_eff} · Сила соперника: {tr.opponent_eff}</p><button type="button" id="tug-pull" onClick={()=>controller.pull(tr)}>🪢 Рывок!</button><p>Рывков: {tr.my_taps} · следующий: +{tr.next_tap_value}</p></>:<>{tr?.status==='finished'&&<p>{tr.outcome==='draw'?'Ничья':tr.outcome==='win_'+tr.my_side?'Победа':'Соперник победил'}</p>}{queued?<p>Ищем противника…</p>:<p>{typeof tug?.rules?.match_sec==='number'?`Матч длится ${tug.rules.match_sec} с.`:'Ожидаем правила сервера.'}</p>}<button type="button" id={queued?'tug-cancel':'tug-find'} disabled={s.busy} onClick={()=>void controller.queue(!!queued)}>{queued?'Отменить поиск':'Найти противника'}</button></>}
      <details><summary>Правила</summary><p>{tug?.rules?.formula_ru}</p><p>{tug?.rules?.reward_ru}</p><p>Организатор — стример этого канала. Apple и Twitch не являются спонсорами и в конкурсе не участвуют.</p></details><Season data={tug?{leaderboard:tug.leaderboard,ends_at:tug.season_ends_at}:null}/>
    </>:room&&st?<><p>@{room.opponent} · {you==='a'?room.player_a_elo:room.player_b_elo} ELO</p>{finished?<h3>{room.winner===client?.identity.login?'Победа':!room.winner?'Ничья':'Поражение'}</h3>:<p>Раунд {Math.min(st.current_round,st.rounds_total)} / {st.rounds_total}</p>}<p>Счёт {st.wins?.[you]} : {st.wins?.[op]}</p>{!finished&&seconds!==null&&<p>{seconds?`Осталось ${seconds} с`:'Ждём подтверждения тайм-аута сервером…'}</p>}
      {st.rating&&<p>ELO: {st.rating.before[you]} → {st.rating.after[you]} ({st.rating.delta[you]>=0?'+':''}{st.rating.delta[you]})</p>}
      {st.version!==2?<p>Данные раунда ещё не получены.</p>:game==='rps'?<><ol>{st.round_outcomes?.map((outcome,i)=><li key={i}>Раунд {i+1}: {moves[st.moves?.[you]?.[i]||'']||'—'} / {outcome?(moves[st.moves?.[op]?.[i]||'']||'—'):st.moves?.[op]?.[i]?'🔒':'—'} · {outcome===you?'победа':outcome===op?'поражение':outcome==='draw'?'ничья':'ожидаем'}</li>)}</ol>{!finished&&<div className="panel-choices">{Object.entries(moves).map(([move,label])=><button type="button" key={move} data-rps-move={move} disabled={!controller.canMove()} onClick={()=>void controller.move(move,room)}>{label}</button>)}</div>}</>:<><ol>{st.boards?.map((board,i)=><li key={i}>Раунд {i+1}: {board.winner===you?'победа':board.winner===op?'поражение':board.winner==='draw'?'ничья':'играем'}</li>)}</ol><div className="community-board" style={{gridTemplateColumns:`repeat(${st.board_size||Math.sqrt(st.boards?.at(-1)?.cells.length||1)},1fr)`}}>{st.boards?.at(-1)?.cells.map((mark,i)=><button type="button" key={i} data-ttt-cell={i} aria-label={'Клетка '+(i+1)} disabled={!controller.canMove()||!!mark} onClick={()=>void controller.move(i,room)}>{mark==='a'?'❌':mark==='b'?'⭕':'·'}</button>)}</div>{!finished&&<p>{controller.canMove()?'Твой ход':'Ожидаем ход соперника'}</p>}</>}
      {finished&&<button type="button" id={prefix+'-new-game-btn'} onClick={()=>controller.again()}>Сыграть ещё</button>}
    </>:s.queue?<><p>{queued?`Ищем противника… Позиция: ${s.queue.queue_position??'—'} · ELO ${s.queue.elo_at_queue??'—'}`:'Найди соперника для новой игры.'}</p><button type="button" id={game==='rps'?queued?'rps-leave-btn':'rps-queue-btn':queued?'ttt-cancel-btn':'ttt-find-btn'} disabled={s.busy} onClick={()=>void controller.queue(!!queued)}>{queued?'Отменить поиск':'Найти противника'}</button></>:<p>Загрузка…</p>}
    {game!=='tug'&&<Season data={s.leaderboard}/>}<button type="button" id={game==='tug'?'tug-close':prefix+'-close-btn'} onClick={()=>{controller.close();onClose?.();}}>Закрыть</button>
  </section>;
}
