import {useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import type {ViewerRuntime} from './runtime';
import {ConfirmDialog} from './ConfirmDialog';
interface Status {married:boolean;partner?:string}
export function SocialFamilyView({runtime,onClose}:{runtime:ViewerRuntime;onClose?:()=>void}){
  const {client,config}=useSyncExternalStore(runtime.subscribe,runtime.snapshot),owner=client?JSON.stringify([client.identity.channelId,client.identity.login]):'';
  const [status,setStatus]=useState<Status|null>(null),[proposals,setProposals]=useState<string[]>([]),[online,setOnline]=useState<string[]>([]),[target,setTarget]=useState(''),[message,setMessage]=useState(''),[closed,setClosed]=useState(false),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState<string|null>(null);
  const snapshot=useRef(status),incoming=useRef(proposals),live=useRef(false),locked=useRef(false),revision=useRef(0),scope=useRef(owner);snapshot.current=status;incoming.current=proposals;
  const nowClient=()=>runtime.snapshot().client;
  const current=()=>live.current&&scope.current===JSON.stringify([nowClient()?.identity.channelId,nowClient()?.identity.login]);
  const price=()=>runtime.snapshot().config?.divorce_cost;
  const hasPrice=()=>typeof price()==='number'&&Number.isFinite(price())&&Number(price())>=0;
  const quote=()=>JSON.stringify([scope.current,snapshot.current?.partner,price()]);
  const load=async()=>{const c=nowClient();if(!c||!current())return;const seq=++revision.current;try{const data=await c.read<Status>('/api/marriage/status/'+c.identity.login);if(!current()||c!==nowClient()||seq!==revision.current)return;snapshot.current=data;setStatus(data);if(data.married){incoming.current=[];setProposals([]);return;}let list:string[]=[];try{const p=await c.read<{proposals?:string[]}>('/api/marriage/proposals/'+encodeURIComponent(c.identity.login));list=Array.isArray(p.proposals)?p.proposals:[];}catch(e){if(current())setMessage(e instanceof Error?e.message:'Предложения не загружены');}if(!current()||c!==nowClient()||seq!==revision.current)return;const o=await c.read<{users?:string[]}>('/api/viewer/online-list');if(!current()||c!==nowClient()||seq!==revision.current)return;incoming.current=list;setProposals(list);setOnline((o.users||[]).filter(u=>u!==c.identity.login));}catch(e){if(current()&&seq===revision.current)setMessage(e instanceof Error?e.message:'Сеть недоступна');}};
  useLayoutEffect(()=>{live.current=true;scope.current=owner;setStatus(null);setProposals([]);setTarget('');setClosed(false);setConfirmation(null);void load();return()=>{live.current=false;revision.current++;};},[runtime,owner]);
  useLayoutEffect(()=>{if(confirmation&&(!current()||confirmation!==quote()||!hasPrice()))setConfirmation(null);},[config,status,owner]);
  const submit=async(kind:'propose'|'reject'|'divorce',from='')=>{const c=nowClient();if(!c||!current()||locked.current)return;if(kind==='propose'&&(!target||target===c.identity.login||!online.includes(target)))return;if(kind==='reject'&&!incoming.current.includes(from))return;if(kind==='divorce'&&(!snapshot.current?.married||!hasPrice()||confirmation!==quote()))return;setConfirmation(null);locked.current=true;setBusy(true);try{const body=kind==='propose'?{username:c.identity.login,target}:kind==='reject'?{from_user:from}:{username:c.identity.login};const reply=await c.post<{success:boolean;message?:string}>('/api/marriage/'+kind,body);if(!current()||c!==nowClient())return;setMessage((reply.success&&kind==='propose'?'Заявка отправлена. Ждём ответа. ':'')+(reply.message||(!reply.success?'Сервер отказал в действии':'')));if(reply.success){if(kind==='reject')await load();else{setClosed(true);if(kind==='divorce')void c.refreshUser().catch(e=>{if(current())setMessage(e.message);});}}}catch(e){if(current())setMessage(e instanceof Error?e.message:'Сеть недоступна. Результат запроса неизвестен.');}finally{locked.current=false;if(current())setBusy(false);}};
  return <section className="panel-card" aria-label="Семья зрителей"><h2>Семья зрителей</h2>{message&&<p role="status">{message}</p>}{!closed&&(status?status.married?<><p>Ты в браке с @{status.partner}</p><button type="button" disabled={busy||!hasPrice()} onClick={()=>setConfirmation(quote())}>Развестись</button>{!hasPrice()&&<p>Цена развода не получена.</p>}</>:<><p>Брак — это статус и социальная связь.</p>{proposals.length>0&&<><h3>Входящие предложения</h3><p>Приём предложений временно недоступен: сервис пока не подтверждает выбранного человека.</p>{proposals.map(from=><article key={from}><p>@{from} предлагает брак</p><div className="panel-choices"><button type="button" data-accept-family={from} disabled>Принять @{from}</button><button type="button" data-reject-family={from} disabled={busy} onClick={()=>void submit('reject',from)}>Отклонить @{from}</button></div></article>)}</>}<label htmlFor="social-family-target">Кому предложить брак</label><select id="social-family-target" value={target} onChange={e=>setTarget(e.currentTarget.value)}><option value="">Выбери зрителя</option>{online.map(u=><option key={u} value={u}>{u}</option>)}</select>{!online.length&&<p>Нет зрителей онлайн.</p>}<button type="button" disabled={busy||!target} onClick={()=>void submit('propose')}>Предложить</button></>:<p>Загрузка…</p>)}<button type="button" onClick={()=>{setClosed(true);onClose?.();}}>Закрыть</button>{confirmation&&<ConfirmDialog title="Расторгнуть брак" cancel={()=>setConfirmation(null)} confirm={()=>void submit('divorce')}><p>Расторгнуть брак с @{status?.partner}? Подача заявления стоит {String(price())} 💎.</p></ConfirmDialog>}</section>;
}
