export interface ColonyConfig { action_prices?: Record<string, number>; item_catalog?: Partial<Record<'give_item' | 'supply' | 'min_stock', [string, string][]>> }
export interface ColonyRequest { id?: string; text: string; deliverable?: boolean }
export interface Colonist { success: boolean; message?: string; linked: boolean; citizen_id?: number; name?: string; job?: string; hp?: number; status?: string; skills?: Record<string, number>; state?: { job?: string; hp?: number; max_hp?: number; saturation?: number; sick?: boolean; hurt?: boolean; asleep?: boolean; paused?: boolean; idle?: boolean; happiness?: number; has_home?: boolean; female?: boolean; child?: boolean; skills?: Record<string, number>; requests?: (ColonyRequest | string)[] } }
export interface Capacity { success: boolean; message?: string; stale?: boolean; data_age_sec?: number; jobs?: { job: string; free: number; total: number }[]; free_beds?: number | null; targets?: { researches?: { branch: string; id: string; name?: string; state: string }[]; buildings?: { pos: string; type: string; backlog: number }[]; min_stock?: { warehouse?: boolean }; can_build?: boolean; upgradable?: { pos: string; type: string; level: number; in_progress?: boolean }[] } }
// Protocol action names, not a client price or item catalog. A missing server
// quote keeps the corresponding action disabled; no fallback catalog is used.
export const colonyActions = [
  ['spawn', 'colonist.spawn', 'Создать колониста', 'me'], ['job', 'colonist.assign_job', 'Назначить работу', 'me'], ['home', 'colonist.assign_home', 'Дать дом', 'me'], ['xp', 'colonist.add_xp', 'Прокачать навык', 'me'], ['fulfill', 'colonist.fulfill_request', 'Выполнить просьбу', 'me'],
  ['feed', 'colonist.feed', 'Покормить', 'me'], ['cure', 'colonist.cure_disease', 'Вылечить болезнь', 'me'], ['heal', 'colonist.heal', 'Исцелить', 'me'], ['mourn', 'colonist.clear_mourn', 'Снять траур', 'me'], ['happiness', 'colonist.happiness_boost', 'Поднять настроение', 'me'], ['auto_work', 'colonist.auto_work', 'Включить автоматическую работу', 'me'],
  ['give_item', 'colonist.give_item', 'Выдать предмет', 'me'], ['set_gender', 'colonist.set_gender', 'Сменить пол', 'me'], ['teleport', 'colonist.teleport', 'Призвать к центру колонии', 'me'],
  ['equip_leather', 'colonist.equip_leather', 'Кожаная броня', 'gear'], ['equip_iron', 'colonist.equip_iron', 'Железная броня', 'gear'], ['equip_diamond', 'colonist.equip_diamond', 'Алмазная броня', 'gear'], ['equip_netherite', 'colonist.equip_netherite', 'Незеритовая броня', 'gear'], ['give_tools', 'colonist.give_tools', 'Выдать инструменты', 'gear'], ['equip_weapon', 'colonist.equip_weapon', 'Выдать оружие', 'gear'], ['give_shield', 'colonist.give_shield', 'Выдать щит', 'gear'], ['set_guard_task', 'colonist.set_guard_task', 'Боевая задача', 'gear'], ['set_guard_retreat', 'colonist.set_guard_retreat', 'Настроить отступление', 'gear'],
  ['festival', 'colony.festival', 'Фестиваль', 'colony'], ['spawn_visitor', 'colony.spawn_visitor', 'Позвать гостя', 'colony'], ['quest_unlock', 'colony.quest_unlock', 'Открыть квест', 'colony'], ['spy_boost', 'colony.spy_boost', 'Усилить шпионов', 'colony'], ['start_research', 'colony.start_research', 'Начать исследование', 'colony'], ['finish_research', 'colony.finish_research', 'Завершить исследование', 'colony'], ['supply', 'colony.supply', 'Снабдить колонию', 'colony'], ['min_stock', 'colony.set_minimum_stock', 'Закрепить запас', 'colony'], ['clear_backlog', 'colony.clear_backlog', 'Разобрать очередь здания', 'colony'], ['upgrade_building', 'colony.upgrade_building', 'Улучшить здание', 'colony'],
] as const;
export type ColonyKind = typeof colonyActions[number][0];
