<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShedLink.Manager.Core\ShedLink.Manager.Core.csproj" />
    <Content Include="..\..\..\manifests\installation\rimworld-0.1.0.json"
             Link="Release\rimworld-0.1.0.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
