using System;
using BannerlordLink.Behaviors;
using BannerlordLink.Actions;
using BannerlordLink.Util;
using TaleWorlds.MountAndBlade;
using TaleWorlds.Engine;
using TaleWorlds.Library;
using Newtonsoft.Json.Linq;
class Program {
 static int failed,total; static HeroDetachmentBehavior b; static Agent a; static Team foe; static Mission m;
 static void Setup(){m=Mission.Current=new Mission(); b=new();m.MissionBehaviors.Add(b);b.OnBehaviorInitialize();a=new Agent{Index=1,Team=new Team()};m.Agents.Add(a);foe=new Team();HeroLookup.Hero=new();a.Character=HeroLookup.Hero.CharacterObject;ActionFeedback.Applied=ActionFeedback.Failed=0;Agent.Main=null;}
 static void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 static void Test(string name,Action test){total++;Setup();try{test();Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+e.Message);}}
 static Agent Enemy(int i,float x,bool human=true,bool mounted=false){var e=new Agent{Index=i,Team=foe,Position=new Vec3(x,0),IsHuman=human};if(mounted)e.MountAgent=new Agent{IsHuman=false};m.Agents.Add(e);return e;}
 static string Status()=>typeof(HeroDetachmentBehavior).GetMethod("GetOrderStatus")?.Invoke(b,new object[]{a}) as string ?? "unsupported";
 static float X()=>a.Scripted?.Position.x??float.NaN;
 static void Main(){
 Test("gate chooses gate despite closer ladder",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="ladder",GlobalPosition=new(5,0),ScriptType=typeof(SiegeLadder)});m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});Check(b.Gate(a),"gate rejected");Check(X()==20,"selected ladder instead of gate");});
 foreach(var walls in new[]{false,true}){Test((walls?"walls":"gate")+" outside siege leaves agent untouched",()=>{Check(!(walls?b.Walls(a):b.Gate(a)),"accepted invalid siege order");Check(!b.IsDetached(a)&&a.ScriptCalls==0,"invalid order detached/pinned hero");});Test((walls?"walls":"gate")+" missing target leaves agent untouched",()=>{m.IsSiegeBattle=true;Check(!(walls?b.Walls(a):b.Gate(a)),"accepted absent target");Check(!b.IsDetached(a)&&a.ScriptCalls==0,"missing target detached/pinned hero");});}
 Test("hold native failure rejected and not retained",()=>{a.ThrowScript=true;Check(!b.Hold(a),"reported success despite native exception");Check(!b.IsDetached(a),"failed hold retained state");});
 Test("attach native failure retains state",()=>{Check(b.Hold(a),"hold failed");a.ThrowDisable=true;Check(!b.Attach(a),"reported successful attach");Check(b.IsDetached(a),"lost control state after failed attach");});
 Test("attach handler refunds failure",()=>{b.Hold(a);a.ThrowDisable=true;new AttachHandler().ExecuteAsync(new JObject{{"target","viewer"}}).GetAwaiter().GetResult();Check(ActionFeedback.Applied==0&&ActionFeedback.Failed==1,"failed attach acknowledged applied");});
 Test("hold handler refunds native failure",()=>{a.ThrowScript=true;new HoldHandler().ExecuteAsync(new JObject{{"target","viewer"}}).GetAwaiter().GetResult();Check(ActionFeedback.Applied==0&&ActionFeedback.Failed==1,"failed hold acknowledged applied");});
 Test("foot charge ignores loose horse",()=>{Enemy(2,5,false);Enemy(3,15);Check(b.Charge(a),"charge rejected");Check(X()==15,"targeted horse");});
 Test("foot charge prefers infantry over cavalry",()=>{Enemy(2,7,true,true);Enemy(3,15);Check(b.Charge(a),"charge rejected");Check(X()==15,"chasing cavalry over reachable infantry");});
 Test("foot charge rejects unreachable infantry",()=>{Enemy(2,8);Enemy(3,15);m.Scene.PathExists=(from,to)=>to.Position.x!=8;Check(b.Charge(a),"charge rejected");Check(X()==15,"targeted inaccessible infantry");});
 Test("foot charge retains target through nearby switch",()=>{Enemy(2,12);var other=Enemy(3,13);b.Charge(a);other.Position=new(11,0);m.CurrentTime=.6f;b.OnMissionTick(.6f);Check(X()==12,"target switched from small distance change");});
 Test("foot charge gives up distant cavalry",()=>{Enemy(2,40,true,true);b.Charge(a);Check(X()==0,"chasing distant cavalry");});
 Test("invalid siege order preserves existing charge",()=>{Enemy(2,15);b.Charge(a);int calls=a.ScriptCalls;Check(!b.Gate(a),"accepted non siege gate");Check(X()==15&&a.ScriptCalls==calls&&b.IsDetached(a),"changed existing command");m.CurrentTime=1;b.OnMissionTick(1);Check(X()==15,"prior charge no longer running");});
 Test("charge gives up stalled nearby cavalry",()=>{Enemy(2,10,true,true);b.Charge(a);Check(X()==10,"nearby cavalry should be eligible");m.CurrentTime=5;b.OnMissionTick(5);Check(X()==0,"stalled cavalry pursuit was not abandoned");});
 Test("charge releases movement for melee contact",()=>{Enemy(2,3);b.Charge(a);Check(a.Scripted==null,"still forcing movement in melee contact");});
 Test("charge cannot engage through obstruction",()=>{Enemy(2,3);m.Scene.BlockLos=true;b.Charge(a);Check(a.Scripted!=null,"released into melee despite blocked contact");});
 Test("charge reselects dead target",()=>{var e=Enemy(2,12);Enemy(3,18);b.Charge(a);e.Active=false;m.CurrentTime=1;b.OnMissionTick(1);Check(X()==18,"dead target retained");});
 Test("mounted charge keeps original nearest target policy",()=>{a.MountAgent=new Agent{IsHuman=false};Enemy(2,8,true,true);Enemy(3,15);b.Charge(a);Check(X()==8,"mounted charge changed by infantry policy");});
 Test("gate without gate never substitutes ladder",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="ladder",GlobalPosition=new(5,0),ScriptType=typeof(SiegeLadder)});Check(!b.Gate(a),"accepted ladder as gate");Check(!b.IsDetached(a)&&a.ScriptCalls==0,"failed gate changed movement");});
 Test("attach success releases control and state",()=>{b.Hold(a);Check(b.Attach(a),"attach rejected");Check(!b.IsDetached(a)&&a.Scripted==null,"attach did not release state/movement");});
 Test("hold success acknowledged once",()=>{new HoldHandler().ExecuteAsync(new JObject{{"target","viewer"}}).GetAwaiter().GetResult();Check(ActionFeedback.Applied==1&&ActionFeedback.Failed==0,"hold feedback wrong");Check(b.IsDetached(a)&&X()==0,"hold not active");});
 Test("gate native failure refunds without retained state",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});a.ThrowScript=true;new GateHandler().ExecuteAsync(new JObject{{"target","viewer"}}).GetAwaiter().GetResult();Check(ActionFeedback.Applied==0&&ActionFeedback.Failed==1,"failed gate acknowledged applied");Check(!b.IsDetached(a),"failed gate retained state");});
 Test("charge uses ordinary movement flag",()=>{Enemy(2,15);b.Charge(a);Check(a.LastFlags==Agent.AIScriptedFrameFlags.NeverSlowDown,"unexpected movement flags");});
 Test("failed replacement restores previous hold",()=>{b.Hold(a);a.Position=new(10,0);a.ScriptFailuresRemaining=1;Check(!b.Hold(a),"failed replacement reported applied");Check(b.IsDetached(a)&&X()==0,"prior hold not restored");m.CurrentTime=1;b.OnMissionTick(1);Check(X()==0,"new failed hold leaked into reissue");});
 Test("failed charge replacement restores prior hold",()=>{b.Hold(a);Enemy(2,15);a.ScriptFailuresRemaining=1;Check(!b.Charge(a),"failed charge reported applied");Check(b.IsDetached(a)&&X()==0,"prior hold lost");m.CurrentTime=1;b.OnMissionTick(1);Check(X()==0,"failed charge became active later");});
 Test("waiting charge reacquires spawned infantry",()=>{Check(b.Charge(a),"empty charge rejected");Check(Status()=="waiting_target"&&X()==0,"did not wait in place");Enemy(2,15);m.CurrentTime=1;b.OnMissionTick(1);Check(Status()=="approaching"&&X()==15,"new infantry not acquired");});
 Test("horse-only battlefield keeps infantry waiting",()=>{Enemy(2,5,false);b.Charge(a);Check(Status()=="waiting_target"&&X()==0,"horse-only battlefield caused pursuit");});
 Test("target death in melee resets contact phase",()=>{var e=Enemy(2,3);Enemy(3,5);b.Charge(a);Check(Status()=="engaged","not engaged");e.Active=false;m.CurrentTime=1;b.OnMissionTick(1);Check(Status()=="approaching"&&X()==5,"new target inherited melee contact phase");});
 Test("charge rechecks target reachability",()=>{Enemy(2,12);Enemy(3,15);b.Charge(a);m.Scene.PathExists=(from,to)=>to.Position.x!=12;m.CurrentTime=2.1f;b.OnMissionTick(2.1f);Check(X()==15,"lost path did not replace target");});
 Test("player controller rejected without mutation",()=>{a.Controller=Agent.ControllerType.Player;Check(!b.Hold(a)&&!b.IsDetached(a)&&a.ScriptCalls==0,"took over player");});
 Test("main agent rejected without mutation",()=>{Agent.Main=a;Check(!b.Charge(a)&&!b.IsDetached(a)&&a.ScriptCalls==0,"took over main agent");});
 Test("gate arrival stops reissuing movement",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});b.Gate(a);a.Position=new(19,0);m.CurrentTime=1;b.OnMissionTick(1);Check(Status()=="arrived"&&a.Scripted!=null&&X()==20,"arrival released the hero back to formation");m.CurrentTime=2;b.OnMissionTick(1);Check(Status()=="arrived"&&X()==20,"arrived hero left the reached spot");});

 // 26.09, владелец: «к стенам»/«к воротам» логично и в защите, и в атаке. Карта: двор x<0,
 // поле x>0; внешние ворота x=10, внутренние x=0, защитники у ворот на 5 м ближе ко двору.
 Test("gate defender holds the intact outer gate from inside",()=>{m.IsSiegeBattle=true;a.Team.Side=TaleWorlds.Core.BattleSideEnum.Defender;a.Position=new(-30,0);CastleGate.At(10,true,false);CastleGate.At(0,false,false);Check(b.Gate(a),"gate rejected");Check(X()==5,"defender not at the outer gate's inner side: "+X());});
 Test("gate defender falls back to the inner gate when the outer is broken",()=>{m.IsSiegeBattle=true;a.Team.Side=TaleWorlds.Core.BattleSideEnum.Defender;a.Position=new(-30,0);var outer=CastleGate.At(10,true,false);CastleGate.At(0,false,false);b.Gate(a);outer.IsGateOpen=true;m.CurrentTime=4;b.OnMissionTick(4);Check(X()==-5,"defender did not retreat to the inner gate: "+X());});
 Test("gate attacker waits outside the closed outer gate",()=>{m.IsSiegeBattle=true;a.Position=new(40,0);CastleGate.At(10,true,false);CastleGate.At(0,false,false);Check(b.Gate(a),"gate rejected");Check(X()==14,"attacker not outside the outer gate: "+X());});
 Test("gate attacker breaks through when all gates fall",()=>{m.IsSiegeBattle=true;a.Position=new(40,0);CastleGate.At(10,true,true);CastleGate.At(0,false,true);Enemy(2,-20);Check(b.Gate(a),"gate rejected");Check(X()==-5,"attacker not sent into the courtyard: "+X());a.Position=new(-5,0);m.CurrentTime=1;b.OnMissionTick(1);Check(Status()!="arrived"&&Status()!="gate","breach did not turn into a charge: "+Status());});
 Test("walls defender goes where the enemy climbs",()=>{m.IsSiegeBattle=true;a.Team.Side=TaleWorlds.Core.BattleSideEnum.Defender;var near=new Agent{Index=5,Team=a.Team,Position=new Vec3(2,0,5)};var far=new Agent{Index=6,Team=a.Team,Position=new Vec3(40,0,5)};m.Agents.Add(near);m.Agents.Add(far);Enemy(7,42);Check(b.Walls(a),"walls rejected");Check(X()==40,"defender sent to the quiet section: "+X());});
 Test("walls attacker without a way up goes to a raised ladder",()=>{m.IsSiegeBattle=true;a.Position=new(60,0);var ladder=new SiegeLadder{State=SiegeLadder.LadderState.OnWall};ladder.GameEntity.GlobalPosition=new Vec3(30,0);m.ActiveMissionObjects.Add(ladder);var idle=new SiegeLadder{State=SiegeLadder.LadderState.OnLand};idle.GameEntity.GlobalPosition=new Vec3(55,0);m.ActiveMissionObjects.Add(idle);Check(b.Walls(a),"walls rejected");Check(X()==30,"attacker not sent to the raised ladder: "+X());});
 Test("gate stall stops repeated movement",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});b.Gate(a);m.CurrentTime=7;b.OnMissionTick(7);Check(Status()=="blocked"&&a.Scripted==null,"stall not reported/stopped");int calls=a.ScriptCalls;m.CurrentTime=8;b.OnMissionTick(1);Check(a.ScriptCalls==calls,"blocked movement repeated");Check(b.Hold(a)&&Status()=="hold","cannot replace blocked command");});
 Test("native error on reissue blocks and stops",()=>{Enemy(2,15);b.Charge(a);a.ThrowScript=true;m.CurrentTime=1;b.OnMissionTick(1);Check(Status()=="blocked"&&a.Scripted==null,"native failure continued silently");});
 Test("gate path loss stops movement",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});b.Gate(a);m.Scene.PathExists=(from,to)=>false;m.CurrentTime=1;b.OnMissionTick(1);Check(Status()=="blocked"&&a.Scripted==null,"lost path did not block");});
 Test("failed attach restores pinned skirmish movement",()=>{Enemy(2,25);Check(b.Skirmish(a)&&X()==0,"skirmish not pinned");a.ThrowCombatOnce=true;Check(!b.Attach(a),"failed combat release accepted");Check(b.IsDetached(a)&&X()==0,"pinned skirmish state survived but movement lost");});
 Test("siege detour movement is progress",()=>{m.IsSiegeBattle=true;m.Scene.Entities.Add(new(){Name="gate",GlobalPosition=new(20,0),ScriptType=typeof(CastleGate)});b.Gate(a);for(int t=1;t<=8;t++){a.Position=new(0,t*2);m.CurrentTime=t;b.OnMissionTick(1);}Check(Status()!="blocked"&&a.Scripted!=null,"valid moving detour incorrectly stalled");});
 Test("long melee contact does not age pursuit timeout",()=>{var e=Enemy(2,3);b.Charge(a);m.CurrentTime=10;b.OnMissionTick(10);e.Position=new(7,0);m.CurrentTime=11;b.OnMissionTick(1);m.CurrentTime=11.6f;b.OnMissionTick(.6f);Check(Status()=="approaching"&&X()==7,"contact time caused immediate pursuit blacklist");});
 Test("unreachable target search bounded and backed off",()=>{for(int i=2;i<102;i++)Enemy(i,i);m.Scene.PathExists=(from,to)=>false;b.Charge(a);Check(m.Scene.PathCalls<=12,"unbounded native path calls: "+m.Scene.PathCalls);int calls=m.Scene.PathCalls;m.CurrentTime=.5f;b.OnMissionTick(.5f);Check(m.Scene.PathCalls==calls,"repeated empty search before one second");});
 Test("empty target search waits one second",()=>{Enemy(2,15);m.Scene.PathExists=(from,to)=>false;b.Charge(a);int calls=m.Scene.PathCalls;Check(calls>0,"path search not exercised");m.CurrentTime=.5f;b.OnMissionTick(.5f);Check(m.Scene.PathCalls==calls,"empty target search repeated after half second");});
 Test("bounded search eventually reaches distant valid candidate",()=>{for(int i=0;i<60;i++)Enemy(i+2,i+5);Enemy(100,100);m.Scene.PathExists=(from,to)=>to.Position.x==100;bool found=false;int before=m.Scene.PathCalls;b.Charge(a);Check(m.Scene.PathCalls-before<=12,"initial search exceeded budget");for(int t=1;t<=10&&!found;t++){before=m.Scene.PathCalls;m.CurrentTime=t;b.OnMissionTick(1);Check(m.Scene.PathCalls-before<=12,"tick search exceeded budget");found=X()==100;}Check(found,"unreachable candidates starved reachable infantry");});
 Test("skirmish retreat persists past next tick",()=>{Enemy(2,10);b.Skirmish(a);float target=X();Check(target<0,"no retreat");m.CurrentTime=.6f;b.OnMissionTick(.6f);Check(X()==target,"retreat cancelled next tick");});
 Test("skirmish unreachable retreat holds",()=>{Enemy(2,10);m.Scene.PathExists=(from,to)=>false;b.Skirmish(a);Check(X()==0,"retreated into unreachable position");});
 Test("skirmish ignores loose horses",()=>{Enemy(2,7,false);Enemy(3,25);b.Skirmish(a);Check(X()==0,"retreat from horse");});
 Test("skirmish finite retreat budget survives distant enemy",()=>{var e=Enemy(2,10);b.Skirmish(a);for(int i=0;i<3;i++){a.Position=new(X(),0);m.CurrentTime=i*10+1;b.OnMissionTick(1);e.Position=new(a.Position.x+10,0);m.CurrentTime=i*10+5;b.OnMissionTick(4);}a.Position=new(X(),0);e.Position=new(a.Position.x+100,0);m.CurrentTime=40;b.OnMissionTick(10);e.Position=new(a.Position.x+10,0);m.CurrentTime=45;b.OnMissionTick(5);Check(X()==a.Position.x,"distance reset retreat budget");});
 Test("skirmish stalled retreat ends and pauses",()=>{Enemy(2,10);b.Skirmish(a);m.CurrentTime=5;b.OnMissionTick(5);Check(X()==0,"stalled retreat continued");m.CurrentTime=5.6f;b.OnMissionTick(.6f);Check(X()==0,"no shooting pause after stall");});
 Test("skirmish arrival starts full shooting pause",()=>{var e=Enemy(2,10);b.Skirmish(a);a.Position=new(X(),0);e.Position=new(a.Position.x+10,0);m.CurrentTime=1;b.OnMissionTick(1);Check(X()==a.Position.x,"arrival not held");m.CurrentTime=3.5f;b.OnMissionTick(2.5f);Check(X()==a.Position.x,"pause ended too soon");m.CurrentTime=4.1f;b.OnMissionTick(.6f);Check(X()<a.Position.x,"next bounded retreat absent");});
 Test("skirmish melee interrupts retreat",()=>{var e=Enemy(2,10);b.Skirmish(a);e.Position=new(3,0);m.CurrentTime=.6f;b.OnMissionTick(.6f);Check(a.Scripted==null,"continued running during melee contact");});
 Test("skirmish retreat deadline bounds moving detour",()=>{Enemy(2,10);b.Skirmish(a);for(int t=1;t<=4;t++){a.Position=new(-t,0);m.CurrentTime=t;b.OnMissionTick(1);}Check(X()==a.Position.x,"retreat exceeded four seconds");});
 Test("failed attach restores active retreat",()=>{Enemy(2,10);b.Skirmish(a);float dest=X();a.ThrowCombatOnce=true;Check(!b.Attach(a),"attach unexpectedly succeeded");Check(X()==dest,"active retreat not restored");});
 Console.WriteLine($"{total-failed}/{total} passed");Environment.ExitCode=failed==0?0:1;
 }
}
