// Wire contracts are server-owned. Unknown fields survive parsing; no economy
// defaults or game catalog enums are synthesized by this presentation layer.
export interface HeroReply { success: boolean; has_hero: boolean; equipment_shop_ready?: boolean; hero?: { hero_id: string; display_name: string; is_alive: boolean | number; is_prisoner?: boolean | number; is_wounded?: boolean | number; level: number; gold: number; [key: string]: unknown }; skills?: { skill_key: string; level: number; focus: number; xp?: number }[]; attributes?: Record<string, number>; [key: string]: unknown }
export interface PanelConfig { focus_tier_costs?: unknown[]; attribute_cost?: unknown; [key: string]: unknown }
export interface BuildReply { success: boolean; enabled: boolean; has_hero: boolean; ready: boolean; pending: boolean; can_manage: boolean; reason?: string | null; message?: string | null; cooldown_remaining_s?: number; build?: { version?: number; specialization?: string; starter_claimed?: boolean; in_battle?: boolean; specializations?: { id: string; label: string; description: string }[]; starter_kits?: { id: string; label: string; items?: { item_id: string; name?: string }[]; available: boolean; reason?: string | null }[]; [key: string]: unknown }; [key: string]: unknown }
export interface ClassesReply { success: boolean; classes: { class_key: string; name: string; description?: string; [key: string]: unknown }[]; current: null | { class_key: string; class_level?: number; primary_skill?: string; primary_skill_level?: number; next_threshold?: number | null }; [key: string]: unknown }
export interface BuffsReply { success: boolean; buffs: { power_key: string; remaining_s: number }[]; cooldowns: { power_key: string; remaining_s: number }[] }
export interface ActionReply { success: boolean; message?: string; cooldown_applied_s?: number; cooldown_remaining_s?: number; required_role?: string; [key: string]: unknown }
export interface ActionOptions { tail: 'hero' | 'balance'; immediateHero?: boolean; successMessage?: string }
export interface PanelState { hero: HeroReply | null; config: PanelConfig | null; build: BuildReply | null; classes: ClassesReply | null; loading: boolean; canAct: boolean; message: string; error: string; errors: Record<string, string>; buildPending: boolean; busy: readonly string[]; cooldowns: Record<string, number>; now: number; generation: number }
export interface PanelTransport { read<T>(path: string, signal?: AbortSignal): Promise<T>; action(type: string, data: Record<string, unknown>): Promise<ActionReply | null> }
export const validPrice = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0;
export const actionKey = (type: string, data: Record<string, unknown>) => type + ':' + Object.keys(data).sort().filter(key => key !== 'client_action_id').map(key => key + '=' + String(data[key])).join('&');

// These five positions reflect the inherited UI cap, not a newly invented price table.
export const hasProgressionPrices = (config: PanelConfig | null) => validPrice(config?.attribute_cost) && Array.isArray(config?.focus_tier_costs) && config.focus_tier_costs.length >= 5 && config.focus_tier_costs.slice(0, 5).every(validPrice);
