import { useLayoutEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { PanelController } from './controller';
import { actionKey } from './contracts';
import { diplomacyAllowed, diplomacyOwner, diplomacyPrice, diplomacyLabel, policies, proposalTargets } from './diplomacy';
import { kingdomInfo } from './party';
const countdown=(rem:number)=>rem>=60?`⏳ ${Math.floor(rem/60)}:${String(rem%60).padStart(2,'0')}`:`⏳ ${rem}с`;
export function DiplomacyView({controller,active}:{controller:PanelController;active:boolean}){
  const s=useSyncExternalStore(controller.subscribe,controller.snapshot),d=s.diplomacy;
  const [peace,setPeace]=useState(false),[policy,setPolicy]=useState(false),[target,setTarget]=useState(''),[tribute,setTribute]=useState('0'),[war,setWar]=useState(''),[peaceVote,setPeaceVote]=useState('');
  const draft=useRef({target:'',tribute:'0'}),details=useRef<Record<string,boolean>>({diplomacy:true}),mounted=useRef(true),selected=useRef(active);selected.current=active;
  const generation=s.generation,context=diplomacyOwner(s),owned=()=>mounted.current&&selected.current&&generation===controller.identityGeneration()&&context===diplomacyOwner(controller.snapshot())&&controller.ready();
  useLayoutEffect(()=>()=>{mounted.current=false;},[]);
  const track=(key:string,open:boolean,section=false)=>{if(open&&!details.current[key])controller.trackSection('bannerlord:'+(section?'section.':'details.')+key);details.current[key]=open;};
  const allowed=(type:string,data:Record<string,unknown>={})=>active&&diplomacyAllowed(s,type,data,s.now)&&!s.busy.includes(actionKey(type,data));
  const perform=(type:string,data:Record<string,unknown>)=>{if(owned()&&diplomacyAllowed(controller.snapshot(),type,data))void controller.diplomacyAction(type,data);};
  const directPeace=()=>{if(!owned())return;const tgt=draft.current.target.trim(),offered_tribute=parseInt(draft.current.tribute,10)||0;if(tgt.length<2){controller.showMessage('Укажи target kingdom (≥2 символа)');return;}if(!diplomacyAllowed(controller.snapshot(),'hero.make_peace'))return;setPeace(false);perform('hero.make_peace',{target_kingdom_id:tgt,target_kingdom_name:tgt,offered_tribute});};
  const warTargets=proposalTargets(s,false),peaceTargets=proposalTargets(s,true),all=kingdomInfo(s.hero)?.all_kingdoms;
  const proposal=(peaceful:boolean)=>{const list=peaceful?peaceTargets:warTargets,id=peaceful?peaceVote:war;return list.find(k=>k.id===id)||list[0];};
  const proposalData=(peaceful:boolean)=>{const row=proposal(peaceful);return {target_kingdom_id:row?.id.trim()||'',target_kingdom_name:(row?.name||row?.id||'').trim()};};
  const propose=(peaceful:boolean)=>{const data=proposalData(peaceful);if(!data.target_kingdom_id)return;perform(peaceful?'kingdom.propose_peace':'kingdom.propose_war',data);};
  const proposalButton=(peaceful:boolean)=>{const type=peaceful?'kingdom.propose_peace':'kingdom.propose_war',seconds=Math.max(0,Math.ceil(((s.cooldowns[type]||0)-s.now)/1000));return <button type="button" id={peaceful?'bnr-peace-vote-propose':'bnr-war-propose'} data-bnr-cd={type} disabled={!allowed(type,proposalData(peaceful))} onClick={()=>propose(peaceful)}>{seconds>0?countdown(seconds):`${peaceful?'🕊':'⚔'} Предложить (${diplomacyLabel(s,type)})`}</button>;};
  if(!d?.has_hero)return <div id="bnr-diplo-slot"/>;
  if(!d.kingdom_id)return <div id="bnr-diplo-slot"><p>🏛 Политика kingdom'а доступна когда герой вступит в королевство</p></div>;
  const canEnact=!!(d.is_king||d.is_clan_leader),enacted=new Set(d.policies_enacted?.map(p=>p.policy_id)),pending=new Set(d.policies_pending?.map(p=>p.policy_id));
  const missingQuotes=[...(canEnact?['hero.enact_policy']:[]),...(d.is_king?['hero.make_peace']:[]),...(canEnact&&warTargets.length?['kingdom.propose_war']:[]),...(canEnact&&peaceTargets.length?['kingdom.propose_peace']:[])].some(type=>diplomacyPrice(s,type)===null);
  return <div id="bnr-diplo-slot"><details className="panel-card" data-bnr-section="diplomacy" open onToggle={e=>track('diplomacy',e.currentTarget.open,true)}><summary>🏛 Политика — {d.kingdom_name||d.kingdom_id}{d.is_king?' 👑 КОРОЛЬ':''}</summary>
    {missingQuotes&&<p className="panel-error" role="status">Цена не загружена. Действия без подтверждённой цены недоступны. <button type="button" data-bnr-diplomacy-retry onClick={()=>{void controller.refreshConfig();}}>Обновить цены</button></p>}
    {!!d.policies_enacted?.length&&<><p>Активные политики:</p><div>{d.policies_enacted.map(p=><span className="panel-policy-badge" key={p.policy_id}>{p.policy_name||p.policy_id}</span>)}</div></>}
    {!!d.policies_pending?.length&&<><p>⏳ На обсуждении:</p><div>{d.policies_pending.map(p=><span className="panel-policy-badge" key={p.policy_id}>{p.policy_name||p.policy_id}</span>)}</div></>}
    {canEnact&&<details data-bnr-details="diplo-policy" open={policy} onToggle={e=>{track('diplo-policy',e.currentTarget.open);setPolicy(e.currentTarget.open);}}><summary>📜 Законы королевства (политики, {diplomacyLabel(s,'hero.enact_policy')})</summary><p>Клик по политике = toggle (активна → отозвать). {diplomacyLabel(s,'hero.enact_policy')} за действие.</p>{policies.map(p=><button type="button" key={p.id} className={'bnr-diplo-policy-row'+(enacted.has(p.id)?' panel-policy-active':'')} data-policy-id={p.id} data-policy-name={p.name} data-policy-pending={pending.has(p.id)?'1':undefined} disabled={pending.has(p.id)||!allowed('hero.enact_policy',{policy_id:p.id,policy_name:p.name})} onClick={()=>perform('hero.enact_policy',{policy_id:p.id,policy_name:p.name})}><strong>{enacted.has(p.id)?'✓ ':''}{p.name}</strong>{pending.has(p.id)?' (на обсуждении)':''}<span className="panel-policy-description">{p.desc}</span></button>)}</details>}
    {d.is_king&&<><details data-bnr-details="diplo-peace" open={peace} onToggle={e=>{track('diplo-peace',e.currentTarget.open);setPeace(e.currentTarget.open);}}><summary>🕊 Предложить peace ({diplomacyLabel(s,'hero.make_peace')})</summary>{peace&&<div id="bnr-diplo-peace-slot"><p>Мод resolve'ит target kingdom по name или StringId. Tribute может быть отрицательным (они платят нам).</p><label>Target kingdom (название или ID):<input id="bnr-peace-target" maxLength={80} value={target} onInput={e=>{draft.current.target=e.currentTarget.value;setTarget(e.currentTarget.value);}} /></label><label>Tribute (золото/день, можно отрицательное):<input id="bnr-peace-tribute" type="number" min={-10000} max={10000} step={100} value={tribute} onInput={e=>{draft.current.tribute=e.currentTarget.value;setTribute(e.currentTarget.value);}} /></label><button type="button" id="bnr-peace-confirm" disabled={!allowed('hero.make_peace',{target_kingdom_id:target.trim(),target_kingdom_name:target.trim(),offered_tribute:parseInt(tribute,10)||0})} onClick={directPeace}>🕊 Заключить ({diplomacyLabel(s,'hero.make_peace')})</button></div>}</details><p>👑 Налог королевства: <strong>{d.kingdom_tax_pct||0}%</strong> — % дневной прибыли вассалов → тебе</p><div className="panel-tax-buttons">{[0,10,25,50].map(pct=><button type="button" key={pct} className="bnr-tax-btn" data-tax-pct={pct} aria-pressed={pct===(d.kingdom_tax_pct||0)} disabled={!allowed('kingdom.set_tax_rate',{tax_rate_pct:pct})} onClick={()=>perform('kingdom.set_tax_rate',{tax_rate_pct:pct})}>{pct}%</button>)}</div></>}
    {canEnact&&Array.isArray(all)&&all.length>0&&<><h3>⚖ Дипломатия — на голосование кланов</h3><p>Это ЗАЯВКА на голосование кланов королевства — не мгновенно и может не пройти. Повторно жать не нужно: следи за статусом войн выше.</p>{warTargets.length>0&&<div><select id="bnr-war-target" aria-label="Предложить войну королевству" value={proposal(false)?.id||''} onChange={e=>setWar(e.currentTarget.value)}>{warTargets.map(k=><option value={k.id} key={k.id}>{k.name||k.id}</option>)}</select>{proposalButton(false)}</div>}{peaceTargets.length>0?<div><select id="bnr-peace-vote-target" aria-label="Предложить голосование о мире" value={proposal(true)?.id||''} onChange={e=>setPeaceVote(e.currentTarget.value)}>{peaceTargets.map(k=><option value={k.id} key={k.id}>{k.name||k.id}</option>)}</select>{proposalButton(true)}</div>:<p>Сейчас ни с кем не воюем — мир предлагать некому.</p>}</>}
  </details></div>;
}
