import { useLayoutEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { PanelController } from './controller';
import { actionKey } from './contracts';
import { kingdomInfo } from './party';
import { kingdomAllowed, kingdomOwner, kingdomQuote, joinLabel, quoteLabel } from './kingdom';
import { PartyDialog } from './PartyView';
export function KingdomView({controller,active}:{controller:PanelController;active:boolean}){
  const s=useSyncExternalStore(controller.subscribe,controller.snapshot),h=s.hero?.hero,ki=kingdomInfo(s.hero),has=!!h?.kingdom_name,rebellion=has&&!!ki&&!ki.is_ruler;
  const [create,setCreate]=useState(false),[join,setJoin]=useState(false),[name,setName]=useState(''),[target,setTarget]=useState('');
  const names=useRef({create:'',join:''}),details=useRef<Record<string,boolean>>({'dyn-kingdom':true}),mounted=useRef(true),selected=useRef(active);selected.current=active;
  const generation=s.generation,context=kingdomOwner(s.hero),owned=()=>mounted.current&&selected.current&&generation===controller.identityGeneration()&&context===kingdomOwner(controller.snapshot().hero)&&controller.ready();
  const [confirm,setConfirm]=useState<{type:string;message:string;quote:string;owns:()=>boolean}|null>(null),pending=useRef(confirm);pending.current=confirm;
  const cancel=()=>{pending.current=null;setConfirm(null);};
  useLayoutEffect(()=>()=>{mounted.current=false;pending.current=null;},[]);
  const permitted=(type:string,data:Record<string,unknown>={})=>active&&kingdomAllowed(s,type)&&!s.busy.includes(actionKey(type,data));
  const perform=(type:string,data:Record<string,unknown>={})=>{if(owned()&&kingdomAllowed(controller.snapshot(),type))void controller.kingdomAction(type,data);};
  const valid=()=>{const c=pending.current;return !!c&&owned()&&c.owns()&&kingdomAllowed(controller.snapshot(),c.type)&&(c.type!=='hero.recruit_vassal_clan'||c.quote===JSON.stringify(kingdomQuote(controller.snapshot(),c.type)));};
  useLayoutEffect(()=>{if(pending.current&&!valid())cancel();},[s,active]);
  const danger=(type:string)=>{if(!owned()||!kingdomAllowed(controller.snapshot(),type))return;const current=controller.snapshot();setConfirm({type,owns:controller.captureRequestOwner(),quote:JSON.stringify(kingdomQuote(current,type)),message:type==='hero.recruit_vassal_clan'?`Нанять вассальный клан за ${quoteLabel(current,type,true)}? Это огромная сумма, вернуть её нельзя. Клан возглавит NPC-лорд и войдёт в твоё королевство.`:ki?.is_ruler?'Покинуть королевство? Ты правитель: королевство будет распущено, а кланы покинут его. Это нельзя отменить.':'Покинуть королевство? Клан потеряет свои владения в королевстве. Обратно примут только новым вступлением, и только если согласятся принять.'});};
  const track=(key:string,open:boolean)=>{if(open&&!details.current[key])controller.trackSection('bannerlord:details.'+key);details.current[key]=open;};
  const submit=(creating:boolean)=>{const type=creating?'hero.create_kingdom':'hero.join_kingdom',kingdom_name=(creating?names.current.create:names.current.join).trim();if(!owned()||!kingdomAllowed(controller.snapshot(),type)||!creating&&!kingdom_name)return;if(creating)setCreate(false);else setJoin(false);perform(type,{kingdom_name});};
  const status=(type:string)=>!kingdomQuote(s,type)&&<div data-bnr-economic-status={type} role="status" className="panel-error">Цена этого действия не загружена. Покупка недоступна. <button type="button" data-bnr-economic-retry={type} onClick={()=>{void controller.refreshConfig();}}>Обновить цены</button></div>;
  const supporters=Array.isArray(ki?.rebellion_supporters)?ki.rebellion_supporters:[],required=Number(ki?.rebellion_supporters_required||2);
  return <details className="panel-card" data-bnr-details="dyn-kingdom" open onToggle={e=>track('dyn-kingdom',e.currentTarget.open)}><summary>👑 Королевство</summary><div id="bnr-kingdom-mgmt-slot"><h2>{has?ki?.name||String(h?.kingdom_name):'— нет королевства —'}</h2>{has&&ki?<dl><dt>👑 Правитель:</dt><dd>{ki.ruler_name||'?'}{ki.is_ruler?' (ты)':''}</dd><dt>🏰 Кланов:</dt><dd>{ki.clans_count||0}</dd><dt>🌆 Поселений:</dt><dd>{ki.fiefs_count||0}</dd><dt>⚔ Война с:</dt><dd>{(ki.at_war_count||0)>0?`${ki.at_war_count} корол.${ki.at_war_names?.length?' ('+ki.at_war_names.join(', ')+')':''}`:'нет'}</dd></dl>:<p>Клан независим — без королевства.</p>}
    {(!has||rebellion&&ki?.is_clan_leader)&&<><details data-bnr-details="kingdom-create" open={create} onToggle={e=>{track('kingdom-create',e.currentTarget.open);setCreate(e.currentTarget.open);}}><summary>{rebellion?`⚔ Поднять восстание (${supporters.length}/${required} сторонников)`:`👑 Создать королевство (${quoteLabel(s,'hero.create_kingdom')})`}</summary>{create&&<div id="bnr-kingdom-create-slot"><p>{rebellion?`Ты заберёшь владения своего клана, а подходящие сторонники перейдут вместе со своими феодами. Сторонники: ${supporters.length}/${required}.`:'Твой независимый клан станет правящим в новом королевстве. Феоды для основания не нужны.'} Списывается {quoteLabel(s,'hero.create_kingdom')} + бонус: 2K влияния и 2M kingdom wallet. Имя получит префикс [BLink].</p><input id="bnr-kingdom-name-input" aria-label="Имя королевства" type="text" maxLength={32} value={name} onInput={e=>{names.current.create=e.currentTarget.value;setName(e.currentTarget.value);}} onKeyDown={e=>{if(e.key==='Enter')submit(true);}} /><button type="button" id="bnr-k-confirm" data-bnr-economic-action="hero.create_kingdom" disabled={!permitted('hero.create_kingdom',{kingdom_name:name.trim()})} onClick={()=>submit(true)}>{rebellion?'⚔ Поднять восстание':'👑 Создать'} ({quoteLabel(s,'hero.create_kingdom')})</button>{status('hero.create_kingdom')}</div>}</details>{rebellion&&<p className={supporters.length<required?'panel-error':''}>{supporters.length?'Сторонники: '+supporters.map(x=>x.name||'?').join(', ')+'.':'Сторонников пока нет.'} Нужны личные вассалы или отношения от +{Number(ki?.rebellion_relation_required||50)} с главой клана.</p>}</>}
    {!has&&<details data-bnr-details="kingdom-join" open={join} onToggle={e=>{track('kingdom-join',e.currentTarget.open);setJoin(e.currentTarget.open);}}><summary>🤝 Вступить в королевство ({joinLabel(s)})</summary>{join&&<div id="bnr-kingdom-join-slot"><p>Введи (часть) имя королевства. Твой clan присоединится как вассал. Списать {joinLabel(s)} динаров.</p><input id="bnr-join-name-input" aria-label="Королевство для вступления" maxLength={64} value={target} onInput={e=>{names.current.join=e.currentTarget.value;setTarget(e.currentTarget.value);}} onKeyDown={e=>{if(e.key==='Enter')submit(false);}} /><button type="button" id="bnr-j-confirm" disabled={!permitted('hero.join_kingdom',{kingdom_name:target.trim()})} onClick={()=>submit(false)}>🤝 Вступить ({joinLabel(s)})</button></div>}</details>}
    {has&&<button type="button" className="bnr-kingdom-leave" disabled={!permitted('hero.leave_kingdom')} onClick={()=>danger('hero.leave_kingdom')}>🚪 Покинуть королевство</button>}
    {has&&ki?.is_ruler&&<><button type="button" className="bnr-recruit-vassal" data-bnr-economic-action="hero.recruit_vassal_clan" disabled={!permitted('hero.recruit_vassal_clan')} onClick={()=>danger('hero.recruit_vassal_clan')}>🛡 Нанять вассальный клан ({quoteLabel(s,'hero.recruit_vassal_clan')})</button>{status('hero.recruit_vassal_clan')}</>}
    {confirm&&<PartyDialog message={confirm.message} cancel={cancel} accept={()=>{const c=pending.current,ok=valid();cancel();if(c&&ok)perform(c.type);}}/>}</div></details>;
}
